// Shared authentication helpers for every Netlify Function in this app.
// Everything here runs server-side only — none of it is ever sent to the
// browser, which is exactly what makes it real security (unlike a
// client-side password check, which anyone can read from the page source).
'use strict';
const crypto = require('crypto');

// Usernames, roles and display names are not secret, so they can live in
// code. The actual password hashes are NOT here — they're read from
// environment variables you set in the Netlify dashboard (Site settings ->
// Environment variables), so they never appear in your Git repository even
// if that repository is public.
const ACCOUNTS = [
  { username: 'shanto',  role: 'developer', name: 'Shanto',  uid: 'user-shanto',  hashEnv: 'AUTH_SHANTO_HASH' },
  { username: 'shomvob', role: 'ceo',       name: 'Shomvob', uid: 'user-shomvob', hashEnv: 'AUTH_SHOMVOB_HASH' },
  { username: 'shoikot', role: 'admin',     name: 'Shoikot', uid: 'user-shoikot', hashEnv: 'AUTH_SHOIKOT_HASH' },
];

const COOKIE_NAME = 'cf_session';
const SESSION_TTL_MS = 8 * 60 * 60 * 1000; // 8 hours

/** Password hashing: Node's built-in scrypt (no external dependency).
 * Stored format is "<saltHex>:<hashHex>", generated by scripts/hash-password.js.
 * Comparison uses crypto.timingSafeEqual to avoid leaking timing info. */
function verifyPassword(password, stored) {
  return new Promise((resolve) => {
    if (!stored || !stored.includes(':')) return resolve(false);
    const [salt, hashHex] = stored.split(':');
    let expected;
    try { expected = Buffer.from(hashHex, 'hex'); } catch (e) { return resolve(false); }
    crypto.scrypt(password || '', salt, expected.length, (err, derivedKey) => {
      if (err) return resolve(false);
      try { resolve(crypto.timingSafeEqual(derivedKey, expected)); }
      catch (e) { resolve(false); }
    });
  });
}

async function checkCredentials(username, password) {
  const u = String(username || '').trim().toLowerCase();
  const acct = ACCOUNTS.find((a) => a.username === u);
  const stored = acct ? process.env[acct.hashEnv] : null;
  if (!acct || !stored) {
    // Still do a dummy scrypt run so an unknown username doesn't respond
    // measurably faster than a known one (basic timing hygiene).
    await verifyPassword(password || '', '00112233445566778899aabbccddeeff:' + '0'.repeat(128));
    return null;
  }
  const ok = await verifyPassword(password, stored);
  return ok ? acct : null;
}

/** Session tokens are a base64url JSON payload plus an HMAC-SHA256
 * signature, keyed by SESSION_SECRET (set in the Netlify dashboard — pick
 * a long random string, e.g. `openssl rand -hex 32`). This is NOT a JWT
 * library, just the same idea implemented directly with Node's crypto, so
 * there's nothing extra to install. */
function b64url(buf) {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
function fromB64url(str) {
  return Buffer.from(str.replace(/-/g, '+').replace(/_/g, '/'), 'base64');
}
function sign(payloadObj) {
  const secret = process.env.SESSION_SECRET;
  if (!secret) throw new Error('SESSION_SECRET is not configured in this site\'s environment variables.');
  const payload = b64url(Buffer.from(JSON.stringify(payloadObj)));
  const sig = b64url(crypto.createHmac('sha256', secret).update(payload).digest());
  return `${payload}.${sig}`;
}
function verify(token) {
  try {
    const secret = process.env.SESSION_SECRET;
    if (!secret || !token) return null;
    const [payload, sig] = token.split('.');
    if (!payload || !sig) return null;
    const expected = b64url(crypto.createHmac('sha256', secret).update(payload).digest());
    // constant-time compare of the signatures
    const a = Buffer.from(sig), b = Buffer.from(expected);
    if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null;
    const data = JSON.parse(fromB64url(payload).toString());
    if (data.exp && Date.now() > data.exp) return null;
    return data;
  } catch (e) { return null; }
}

function cookieFor(token) {
  const maxAge = Math.floor(SESSION_TTL_MS / 1000);
  return `${COOKIE_NAME}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
}
function clearCookie() {
  return `${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`;
}
function getSessionFromEvent(event) {
  const header = (event.headers && (event.headers.cookie || event.headers.Cookie)) || '';
  const match = header.match(new RegExp(`${COOKIE_NAME}=([^;]+)`));
  if (!match) return null;
  return verify(decodeURIComponent(match[1]));
}
function makeSessionToken(acct) {
  return sign({ uid: acct.uid, role: acct.role, name: acct.name, iat: Date.now(), exp: Date.now() + SESSION_TTL_MS });
}

module.exports = { ACCOUNTS, checkCredentials, sign, verify, cookieFor, clearCookie, getSessionFromEvent, makeSessionToken };
