// Shared authentication helpers for the Cloudflare Pages Functions in this
// app. Deliberately built on the standard Web Crypto API only (crypto.subtle,
// crypto.randomUUID) — Cloudflare Workers run a Web-standard JS runtime, NOT
// full Node.js, so Node-only APIs like the scrypt-based version of this file
// (from the Netlify build) will not work here. Everything below runs
// server-side only and is never sent to the browser.
'use strict';

// Usernames, roles and display names aren't secret, so they live in code.
// The actual password hashes are NOT here — they come from environment
// variables/secrets you set in the Cloudflare Pages dashboard, so they never
// appear in your Git repository even if it's public.
export const ACCOUNTS = [
  { username: 'shanto',  role: 'developer', name: 'Shanto',  uid: 'user-shanto',  hashEnv: 'AUTH_SHANTO_HASH' },
  { username: 'shomvob', role: 'ceo',       name: 'Shomvob', uid: 'user-shomvob', hashEnv: 'AUTH_SHOMVOB_HASH' },
  { username: 'shoikot', role: 'admin',     name: 'Shoikot', uid: 'user-shoikot', hashEnv: 'AUTH_SHOIKOT_HASH' },
];

const COOKIE_NAME = 'cf_session';
const SESSION_TTL_MS = 8 * 60 * 60 * 1000; // 8 hours

// ---- small byte/hex/base64url helpers (Web Crypto works in bytes) ----
function hexToBytes(hex) {
  const arr = new Uint8Array(hex.length / 2);
  for (let i = 0; i < arr.length; i++) arr[i] = parseInt(hex.substr(i * 2, 2), 16);
  return arr;
}
function b64url(bytes) {
  let bin = '';
  bytes.forEach((b) => { bin += String.fromCharCode(b); });
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
function fromB64url(str) {
  const bin = atob(str.replace(/-/g, '+').replace(/_/g, '/'));
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}
function constantTimeEqualBytes(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}
function constantTimeEqualStr(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

/** Password hashing: PBKDF2-HMAC-SHA256 via the standard Web Crypto API —
 * the closest native equivalent to Node's scrypt that Workers actually
 * support without extra dependencies. Stored format is
 * "<iterations>:<saltHex>:<hashHex>", generated by scripts/hash-password.js,
 * so the iteration count can change later without breaking old hashes. */
async function verifyPassword(password, stored) {
  if (!stored || stored.split(':').length !== 3) return false;
  const [iterStr, saltHex, hashHex] = stored.split(':');
  const iterations = parseInt(iterStr, 10);
  if (!iterations || iterations < 1000) return false;
  const salt = hexToBytes(saltHex);
  const expected = hexToBytes(hashHex);
  const keyMaterial = await crypto.subtle.importKey('raw', new TextEncoder().encode(password || ''), { name: 'PBKDF2' }, false, ['deriveBits']);
  const derivedBits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations, hash: 'SHA-256' }, keyMaterial, expected.length * 8);
  return constantTimeEqualBytes(new Uint8Array(derivedBits), expected);
}

export async function checkCredentials(username, password, env) {
  const u = String(username || '').trim().toLowerCase();
  const acct = ACCOUNTS.find((a) => a.username === u);
  const stored = acct ? env[acct.hashEnv] : null;
  if (!acct || !stored) {
    // Dummy PBKDF2 run so an unknown username doesn't respond measurably
    // faster than a known one (basic timing hygiene).
    await verifyPassword(password || '', `210000:${'00'.repeat(16)}:${'00'.repeat(32)}`);
    return null;
  }
  const ok = await verifyPassword(password, stored);
  return ok ? acct : null;
}

/** Session tokens: base64url JSON payload + HMAC-SHA256 signature, keyed by
 * the SESSION_SECRET binding (set in the Cloudflare dashboard — any long
 * random string, e.g. from `openssl rand -hex 32`). */
async function hmacSign(payloadB64, secret) {
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payloadB64));
  return b64url(new Uint8Array(sig));
}
export async function makeSessionToken(acct, env) {
  const secret = env.SESSION_SECRET;
  if (!secret) throw new Error("SESSION_SECRET is not configured in this project's environment variables.");
  const payloadObj = { uid: acct.uid, role: acct.role, name: acct.name, iat: Date.now(), exp: Date.now() + SESSION_TTL_MS };
  const payload = b64url(new TextEncoder().encode(JSON.stringify(payloadObj)));
  const sig = await hmacSign(payload, secret);
  return `${payload}.${sig}`;
}
export async function verifySessionToken(token, env) {
  try {
    const secret = env.SESSION_SECRET;
    if (!secret || !token) return null;
    const [payload, sig] = token.split('.');
    if (!payload || !sig) return null;
    const expectedSig = await hmacSign(payload, secret);
    if (!constantTimeEqualStr(sig, expectedSig)) return null;
    const data = JSON.parse(new TextDecoder().decode(fromB64url(payload)));
    if (data.exp && Date.now() > data.exp) return null;
    return data;
  } catch (e) { return null; }
}

export function cookieFor(token) {
  const maxAge = Math.floor(SESSION_TTL_MS / 1000);
  return `${COOKIE_NAME}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
}
export function clearCookie() {
  return `${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`;
}
export async function getSessionFromRequest(request, env) {
  const header = request.headers.get('Cookie') || '';
  const match = header.match(new RegExp(`${COOKIE_NAME}=([^;]+)`));
  if (!match) return null;
  return verifySessionToken(decodeURIComponent(match[1]), env);
}

export function json(statusCode, obj, extraHeaders) {
  return new Response(JSON.stringify(obj), {
    status: statusCode,
    headers: { 'Content-Type': 'application/json', ...(extraHeaders || {}) },
  });
}
